services:
  - type: web
    name: sales-offers-backend
    env: python
    buildCommand: "cd sales_offers_backend && pip install -r requirements.txt"
    startCommand: "cd sales_offers_backend && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_admin && python manage.py make_salesandoffers_admin && gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.snoihkpyoqrffgvkinav:$Sales123Offers$@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "salesandoffers.onrender.com,localhost,127.0.0.1,offersandsales.co.ke,www.offersandsales.co.ke"