services:
  - type: web
    name: sales-offers-backend
    env: python
    buildCommand: "apt-get update && apt-get install -y libpq-dev && pip install -r sales_offers_backend/requirements.txt"
    startCommand: "cd sales_offers_backend && python manage.py migrate && python create_superuser.py && gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sales-offers-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "salesandoffers.onrender.com,localhost,127.0.0.1"

databases:
  - name: sales-offers-db
    databaseName: sales_offers
    user: sales_offers_user